/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Yotam' at '1/25/17 12:55 AM' with Gradle 2.10
 *
 * @author Yotam, @date 1/25/17 12:55 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
